### ISSUE TITLE
Error in running client_lib/lib/test.js

### ISSUE THREAD

**Issue by Romulus10** [InsidiousMind/ethdbg#3]
With the test RPC running in the background, test.js halts with the following error:
```
Error: Invalid number of parameters for "undefined". Got 0 expected 1!
    at Object.InvalidNumberOfParams (/home/sean/Documents/ethdbg/client_lib/node_modules/web3-core-helpers/src/errors.js:32:16)
    at Object._createTxObject (/home/sean/Documents/ethdbg/client_lib/node_modules/web3-eth-contract/src/index.js:681:22)
    at Contract.deploy (/home/sean/Documents/ethdbg/client_lib/node_modules/web3-eth-contract/src/index.js:490:33)
    at deployContract (/home/sean/Documents/ethdbg/client_lib/lib/fork.js:114:12)
    at /home/sean/Documents/ethdbg/client_lib/lib/fork.js:86:5
    at Immediate.<anonymous> (/home/sean/Documents/ethdbg/ganache-core/lib/subproviders/geth_api_double.js:35:9)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```
I'm probably using the entire thing wrong, but I wanted to make a note of this so that I'd know to go back to it later.

**Comment by InsidiousMind** [comment]
fixed, and no longer using test.js
